TOP_DIR=../..
#PROCESS=$(shell ls *.pre)
#HTML=$(patsubst %.html.pre,%.html, $(PROCESS))
INSTALLDIR=$(OUTPUTDIR)/sw/jdt
#OUTPUT=$(addprefix ${INSTALLDIR},$(HTML))
COPYDIRS=

include $(TOP_DIR)/Makefile.common

local-build: 

local-install: 

local-clean: 
