#What is the base URL of the web page?
BASEURL=http://istlab.dmst.aueb.gr/~george/
#The toplevel dir on the web server 
HOST=george@istlab.dmst.aueb.gr:/home/george/public_html

INCLUDE=${TOP_DIR}/include
OUTPUTDIR=${TOP_DIR}/public_html
TOOLS=${TOP_DIR}/tools
TOPLEVEL=${TOP_DIR}/toplevel

#What is the file that stores news in raw format? 
NEWSSRC=${TOP_DIR}/news/news.pre

