<div id="commenu" class="commenu">

  <a href="http://www.linkedin.com/in/georgiosgousios"><img alt="linkedin profile" src="img/linkedin.gif" height='23' border='0'/></a>
  
  <a href="http://www.facebook.com/gousiosg"><img alt="facebook profile" src="img/fb.jpg" height='23' border='0'/></a>

  <a href="http://twitter.com/gousiosg"><img alt="twitter feed" src="img/twitter.gif" height='23' border='0'/></a>
  <!--link:<img alt="rss feed" src="img/rss.png" height='23'  border='0'/>,gousiosg-rss.xml-->
  
  <br/>
  
  <a href="http://dl.acm.org/author_page.cfm?id=81351592431"><img alt="ACM digital library" src="img/acm.jpg" /></a>

  <a href="http://www.informatik.uni-trier.de/~ley/db/indices/a-tree/g/Gousios:Georgios.html"><img alt="DBLP" src="img/dblp.gif" /></a>
  <a href="http://scholar.google.gr/citations?hl=el&user=-NI5S50AAAAJ&oi=sra"><img alt='Google scholar' height='23' src="img/gscholar.gif" width='95'  border='0'/></a>

  <a href="https://github.com/gousiosg"><img alt="Georgios Gousios Github
    account" src="img/github.png" width="80px"/></a>
  
  <a href="http://www.ohloh.net/accounts/21690?ref=Detailed"><img alt='Ohloh profile for gousiosg' height='23' src="http://www.ohloh.net/accounts/21690/widgets/account_detailed.gif" width="95px" border='0'/></a>


</div>
