<div id="commenu" class="commenu">
 <a href="http://www.linkedin.com/in/georgiosgousios">
  <img alt="linkedin profile" src="img/linkedin.gif" height='23' border='0'/>
 </a>
 <a href="http://www.facebook.com/people/Georgios-Gousios/544933039">
  <img alt="facebook profile" src="img/fb.jpg" height='23' border='0'/>
 </a>
 <a href="/gousiosg-news.xml">
  <img alt="rss feed" src="img/rss.png" height='23'  border='0'/>
 </a>
 <br/>
 <a href='http://www.ohloh.net/accounts/21690?ref=Detailed'>
  <img alt='Ohloh profile for gousiosg' height='23' src="http://www.ohloh.net/accounts/21690/widgets/account_detailed.gif" width='95'  border='0'/>
 </a>
</div>
