<div class="footer">
    <hr width="100%"/>	
    <div class="license">
        <!--incl:LICENSE-->
    </div>
    <div class="lastchanged">
        Last Changed:
            <!--changed:date-->
        
     </div>
   <!-- <script src="http://www.google-analytics.com/urchin.js" type="text/javascript"/>
    <script type="text/javascript">
    _uacct = "UA-2510585-1";
    urchinTracker();
    </script>-->
</div>
