<div id="menus" class="navmenu">
        <div class="menuheader">
            Links
        </div>
        <div class="menuitem">
           <!-- <a href="/pubs">Publications</a>-->
            <a href="http://sense.eltrun.gr/publications/m_gousios-publications.html">Publications</a>
        </div>
        <div class="menuitem">
            <!--<a href="/res">Research</a>-->
        </div>
        <div class="menuitem">
            <!--<a href="/sw">Software</a>-->
        </div>
        <div class="menuitem">
            <!--<a href="/projects">Projects</a>-->
        </div>
        <div class="menuitem">
            <!--<a href="/labs">Labs</a>-->
        </div>
        <div class="menuitem">
            <a href="/links.html">Links</a>
        </div>
        <div class="menuitem">
            <a href="/contact.html">Contact</a>
        </div>
        <div>
            <a href="/index.html">Home</a>
        </div>
</div>
