<div id="menus" class="menu">
        <div class="menuheader">
            Links
        </div>
        <div class="menuitem">
           <!-- <a href="/pubs">Publications</a>-->
            <a href="http://sense.eltrun.gr/publications/m_gousios-publications.html">Publications</a>
        </div>
        <div class="menuitem">
            <!--<a href="/res">Research</a>-->
        </div>
        <div class="menuitem">
            <!--<a href="/sw">Software</a>-->
        </div>
        <div class="menuitem">
            <!--<a href="/projects">Projects</a>-->
        </div>
        <div class="menuitem">
            <!--<a href="/labs">Labs</a>-->
        </div>
        <div class="menuitem">
            <a href="/links.html">Links</a>
        </div>
        <div class="menuitem">
            <a href="/contact.html">Contact</a>
        </div>
        <hr width="100%"/>
        <a href="http://www.linkedin.com/in/georgiosgousios">
            <img alt="linkedin profile" src="img/linkedin.gif" height='23' border='0'/>
        </a>
        <a href="http://www.facebook.com/people/Georgios-Gousios/544933039">
            <img alt="facebook profile" src="img/fb.jpg" height='23' border='0'/> 
        </a>
        <a href="/gousiosg-news.xml">
            <img alt="rss feed" src="img/rss.png" height='23'  border='0'/> 
        </a>
        <br/>
        <a href='http://www.ohloh.net/accounts/21690?ref=Detailed'>
        <img alt='Ohloh profile for gousiosg' height='23' 
            src="http://www.ohloh.net/accounts/21690/widgets/account_detailed.gif" width='95'  border='0'/>
        </a>
        <hr width="100%"/>
        <div class="menuitem">
            <a href="/index.html">Home</a>
        </div>
 </div>
