<div id="menus" class="navmenu">
        <div class="menuheader">
            Links
        </div>
        <div class="menuitem">
           <!-- <a href="/pubs">Publications</a>-->
            <a href="http://sense.eltrun.gr/publications/m_gousios-publications.html">Publications</a>
        </div>
        <div class="menuitem">
            <!--1link:Research,res-->
        </div>
        <div class="menuitem">
            <!--1link:Software,sw-->
        </div>
        <div class="menuitem">
            <!--1link:Projects,projects-->
        </div>
        <div class="menuitem">
            <!--1link:Labs,labs-->
        </div>
        <div class="menuitem">
            <!--link:Links,links.html-->
        </div>
        <div class="menuitem">
            <!--link:Contact,contact.html-->
        </div>
        <div class="menuitem">
            <!--link:Home, -->
        </div>
</div>
